[target.thumbv7m-none-eabi]
runner = "arm-none-eabi-gdb -q -x target.gdb -x runner.gdb -ex c"

rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7m-none-eabi"
